version: '2'
services:
  adapter:
    image:
      hdcbc/adapter:develop
    command:
      npm run-script start -- --configFile /tmp/config/config.json --mappingFile /tmp/config/mapping.js --source:database oscar --target:database $TARGET_DATABASE --target:user $TARGET_USER --target:password $TARGET_PASSWORD
    links:
      - db
    volumes:
      - ./config/mapping.js:/tmp/config/mapping.js
      - ./config/config.json:/tmp/config/config.json
      - data-volume:/tmp/:rw
    extra_hosts:
      - "target:$TARGET_HOST"
  db:
    image:
      mysql:5.5
    command:
      mysqld --secure-file-priv="" --sync_binlog=2 --innodb_flush_log_at_trx_commit=2 --innodb_log_file_size="256M" --innodb_flush_method="O_DIRECT" --innodb_buffer_pool_size="1000M"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - ./sh/init.sh:/docker-entrypoint-initdb.d/init.sh
      - $OSCAR_BACKUP_PATH:/sql/oscar_backup.sql
      - $DRUGREF_BACKUP_PATH:/sql/drugref_backup.sql
      - data-volume:/tmp/:rw
volumes:
  data-volume:
